version: '3.8'

services:
  app:
    build:
      context: .
    container_name: momentum
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      REPLICATE_API_TOKEN: "${REPLICATE_API_TOKEN}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"